# Generated by Django 5.2.7 on 2025-10-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=15),
        ),
    ]
