# Generated by Django 5.2.7 on 2025-10-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
