# Generated by Django 5.2.7 on 2025-10-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='key',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_key',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
    ]
