# Generated by Django 5.2.7 on 2025-10-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_key_message_encrypted_key_message_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_key',
        ),
        migrations.RemoveField(
            model_name='message',
            name='iv',
        ),
    ]
