# Generated by Django 5.2.7 on 2025-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_encrypted_key_remove_message_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_key',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
