# Generated by Django 5.2.7 on 2025-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_encrypted_key_message_iv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_key',
            new_name='encrypted_key_recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_key_sender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
