# Generated by Django 5.2.7 on 2025-10-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_encrypted_key_message_encrypted_key_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='gifs/')),
            ],
        ),
    ]
