# Generated by Django 5.2.7 on 2025-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
