# Generated by Django 5.2.7 on 2025-10-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_gif_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='gif',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_key_recipient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_key_sender',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='iv',
            field=models.TextField(blank=True),
        ),
    ]
