# Generated by Django 5.2.7 on 2025-10-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_media_alter_gif_price_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
