# Generated by Django 5.2.7 on 2025-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('gif', 'GIF')], default='text', max_length=10),
            preserve_default=False,
        ),
    ]
